### PR TITLE
Adds guide to joining, expands section on gaining edit access, and updates outdated references throughout

### PR DESCRIPTION
**Pull request by AdultSun**
_(Preview pictures and links for all major changes at the bottom of this comment.)_

## Joining StashDB
With the new invite code system live on StashDB, I've added a new guide on "Accessing StashDB" that includes an embedded invite code. This means that we no longer require new users to join Discord/Matrix *at all* anymore. Everything they need will be here in the docs.

_Edit: The same invite code is listed in StashDB's section of "Accessing Stash-Boxes" now too._

## Contributing to StashDB
However, StashDB *editors* will still be required to use either Discord or Matrix. Hopefully that will no longer be necessary after a notification system is added to Stash and we can change that from a "requirement" to a "recommendation." In the meantime, I've expanded the page on "Contributing to StashDB" since we mostly just redirected people to the pinned messages on Discord before now. Instead, I plan to do the opposite, directing everyone to the new page who doesn't know how to get edit access, didn't mention their username, didn't match their display name and username, or whatever else. I would also want to update the pinned message to direct would-be editors to this page as well. The idea is that this would ensure more users visit the guideline docs at least once before gaining edit access while making it easier in the future to cut Discord/Matrix out of the process entirely. We would only need to make a few updates to this page, removing references to Discord/Matrix related requirements, and possibly directing applicants to an email instead.

## Joining Discord and Matrix
The last major change here is an update to the "Joining Discord" page. It's been renamed and expanded to also include Matrix and explain a few of the more salient differences between the two. I link to Dogma's page in the Stash docs instead of going into too much detail though.

## Everything Else
Finally, I've made various minor changes throughout:
- Reordered the "StashDB" section of the "FAQ / Getting Started" category since I needed to move things around to accomodate the new "Accessing StashDB" page anyway
- Replaced `metadataapi.net` with the new `theporndb.net` domain in their "Accessing Stash-Boxes" table
- Updated StashDB's section of "Accessing Stash-Boxes" to reflect the new changes regarding invite codes
- Replaced all "PHash" spellings with "pHash" for the sake of consistency
- Fixed all internal links to the newly renamed "Joining Discord and Matrix" page

## Previews
image
_Creating a StashDB account, [linked here](https://adultsun.github.io/StashDB-Docs/docs/faq_getting-started/stashdb/accessing-stashdb/)_

---

image
_Connecting StashDB to Stash, [linked here](https://adultsun.github.io/StashDB-Docs/docs/faq_getting-started/stashdb/accessing-stashdb/#connecting-to-stash)_

---

image
_StashDB section of "Accessing Stash-Boxes", [linked here](https://adultsun.github.io/StashDB-Docs/docs/faq_getting-started/stashdb/accessing-stash-boxes/#stashdb)

image
_Gaining edit access, [linked here](https://adultsun.github.io/StashDB-Docs/docs/faq_getting-started/stashdb/contributing-to-stashdb/)_

---

image
_Joining Discord and Matrix, [linked here](https://adultsun.github.io/StashDB-Docs/docs/faq_getting-started/stashdb/joining-discord-and-matrix/)_

### CODE REVIEW

**Comment by Maista6969** [comment]
Looks great! Reading the section on usernames reminded me of the (admittedly rare) problem of users who pick usernames that contain characters that will mess up an URL, like `#` or `/`: should we warn them about this? And now that I think about we should probably raise an issue in the stash-box repo about that, URL-encoding usernames in links should be a pretty simple fix :)

**Comment by AdultSun** [comment]
The last couple of commits implement [Jekyll's "Includes" function](https://jekyllrb.com/docs/includes/) for the embedded invite code. This will allow me to simply edit `invite-code.txt` in the `_includes` folder to update the invite code sections of both the "Accessing StashDB" guide and the newly edited StashDB section of "Accessing Stash-Boxes". Editing the text file will update the same code in both locations at the same time while preserving the correct formatting.

Thanks to peolic for the suggestion.

**Comment by AdultSun** [comment]
> Looks great! Reading the section on usernames reminded me of the (admittedly rare) problem of users who pick usernames that contain characters that will mess up an URL, like `#` or `/`: should we warn them about this? And now that I think about we should probably raise an issue in the stash-box repo about that, URL-encoding usernames in links should be a pretty simple fix :)

Yeah, I agree that should be fixed on the Stash-Box side somehow too. I mention elsewhere that an "admin may also ask you to pick a new username before granting edit access," but that's intended for anyone who makes a username that includes `admin`/`mod`/`sys`/`root`/etc. (happened a few times already) and doesn't help anyone who may have trouble grabbing an API key because the link to their profile page is broken.

I'll add a short warning about it in the meantime, thanks for the heads-up.

**Comment by AdultSun** [comment]
I've updated the screenshots to include the last few updates.

**Pull request merged**
