### PR TITLE
Diacritics in Performer Names

### PR DESCRIPTION
**Pull request by DogmaDragon**
Adding a confirmed guideline. 
Thread: https://discord.com/channels/559159668438728723/1076296943996780565

I tried to not be very verbose, but you might want it to expand it if it's too concise.

### CODE REVIEW

**Comment by AdultSun** [comment]
I expanded on the guideline explanation section a little. I think brevity is less important there, especially since we're planning on re-organizing those sections to be stand-alone pages soon.

The biggest change I made is a shift in framing from "diacritics **should** be used" to "diacritics **may** be used." Otherwise it sounds too much like any alias with diacritic markings should override all other considerations when picking the primary name, which I don't believe was the intention with this guideline. I clarify that everything listed under "Preferred Primary Names" still applies here while linking to that section.

**Comment by DogmaDragon** [comment]
Good point on should, nor sure why I choose it from the `allow` mentioned in the Discord thread. My bad.

**Comment by AdultSun** [comment]
I think this is ready now. Here's a preview of what it'll look like on the website, I'll share it on Discord for any additional feedback before merging it.

image

**Comment by DogmaDragon** [comment]
I like **can be included** more than **are allowed** in the context of this sentence. But I'm good with whatever.

**Comment by AdultSun** [comment]
I just felt like "can be included" was too clunky, especially when I use "included" again at the end of the sentence. When you reminded me of how you used "allow" earlier instead I felt that would allow the sentence to flow better. I don't think there's any significant change in meaning there, just personal preference. I'll leave it as-is for now.

It's been a couple days and I haven't gotten any other comments on the current language, so I'll merge this PR.

**Pull request merged**
